# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  redis-vector-db:
    image: redis/redis-stack:7.4.0-v2@sha256:5b9c55e53a8b74decc26010abc6baaea632e678a07ee5fcb6ff798465ebb00b1
    container_name: redis-vector-db
    runtime: runc
    ports:
      - "6379:6379"
      - "8001:8001"
