{{- if and .Values.tokens.hug_token (not .Values.tokens.hugTokenSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: hf-token-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  HF_TOKEN: {{ .Values.tokens.hug_token | b64enc | quote }}
{{- end }}
